version: '3.9'

services:
  app:
    build: .
    container_name: product-tracker
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-9100}:9100"
    volumes:
      - db_data:/var/lib/postgresql
      - uploads:/app/uploads
    environment:
      SERVER_PORT: 9100
      DB_NAME: product_tracker
      DB_PASS: ${DB_PASS:-1234}
      APP_JWT_SECRET: ${APP_JWT_SECRET:-change_this_to_a_long_random_secret}
      APP_JWT_EXPIRATION: 604800000

volumes:
  db_data:
  uploads:
